name: Arilo Processing Engine CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install Project with Dev Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Black Check
      run: black --check .

    - name: Run Ruff Check
      run: ruff check .

    - name: Run Tests with Pytest
      env:
        GCP_PROJECT_ID: "ci-test-project"
        PUBSUB_SERVICE_ACCOUNT_PATH: "fake/path/to/key.json"
        APP_ENV: "development"
        LLM_SERVICE_ACCOUNT_PATH: "fake/path/to/key.json"
        GCS_SERVICE_ACCOUNT_PATH: "fake/path/to/key.json"
        DB_HOST: "localhost"
        DB_PORT: "5433"
        DB_USER: "postgres"
        DB_PASSWORD: "mypassword"
        DB_NAME: "mydb"
      run: pytest test_app.py